#!/bin/bash 

run_script="run.sh"

if [[ $1 == "-e" ]]; then
    if [[ $2 != "" ]]; then
        run_script="$2"
    fi
fi

if [[ -f "$run_script" && -x "$run_script" ]]; then
    ./$run_script
else
    printf "'$run_script' not found\n"
fi
